### ISSUE TITLE
Add new version to Submit support ticket form

### ISSUE THREAD

**Issue by ManiAkasapu** [DCC-EX/dcc-ex.github.io#174]
Hello,

We rely on Google **Apps Script**, which sends email on submitting the ticket. Now, as we released new version I added that to picklist. Can anybody update the new URL.

Which is this:
https://script.google.com/macros/s/AKfycbznNvvGKt3jEC1gzwrzMTP6Dof9wOUL8wZwr01R1tNsDcdq6aQNnQyCViFocnniTXo/exec

on the **Submit support ticket** page and test if it working fine?

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/3207181/161046879-33d688dd-67e4-4f1c-9203-c8911aadeee5.png">
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/3207181/161047053-4d32a515-b86d-4101-9294-e1029f24a88d.png">

**Comment by ManiAkasapu** [comment]
Currently the script is running on my personal account.. I think it also good to move it to DCC++ EX gmail account. I can help to port if needed.
Thanks

**Comment by ManiAkasapu** [comment]
The new code will be:


```
<iframe src="https://script.google.com/macros/s/AKfycbznNvvGKt3jEC1gzwrzMTP6Dof9wOUL8wZwr01R1tNsDcdq6aQNnQyCViFocnniTXo/exec" 
class="is-fullwidth" height="800" width="100%" style="border:0;">
</iframe>
```

**Comment by FrightRisk** [comment]
Hi Mani. I tried watching the beginning of 2 videos and the first page of the google getting started and still have no idea what this is or how this works. It looks like maybe it is like VBScript that you can run in Microsoft Office applications? So you have to run it inside your own gmail account somewhere? How does clicking on something running on our website link to an email account? Where is the code that generates the page? How is the page created and maintained?

You still have access yourself to the web page, but I'm happy to update it.

As for changing where the script lives, we have no gmail account. I wanted to create a "dcc-ex" account but did not for the following reason:

1. Gmail insists that an email address is at least 6 characters and it can't have a any special characters in it (like our dash). So our name can't be used in gmail. We would have to come up with something like "dccextrains" or "mydccex" or something that I don't think is a good solution
2. There is no way to have a shared email account in google. So I would have to give the password to everyone and that isn't a good solution either because there would be no "admin" account to be able to fix things.
3. I already have to check 4 email accounts every day, I didn't want to have to open another one in another browser window ;)

Right now, I forward the email I created with our domain provider to my "frightrisk" email account that I only use for trains. Maybe I should have created a "dccexsupport" gmail address and used their "delegated" or "collaborative" inbox features? But I haven't had the time to try and research those to see if that could help us. I will email you.

**Comment by ManiAkasapu** [comment]
Hi Fred, 
Hope you are doing well.

Google App script is meant to interact with the Google apps for example, the form Submitted can be stored as a ROW in Google sheet or Send an email or Create a word document from the content submitted. Many possibilities..

The google script (its is basically javascript)  is on my account. It uses my account to authorize. The moment User clicks SUBMIT it triggers this script. And send email to **support@dcc-ex.com**. 

The script provides 

- The form interface (think like a Webform)
- Javascript that sends email to DccEx team
- Thank you page

Maybe create with ID  **dccexsupport@gmail.com** which can be used for this purpose? But you do not need to check it. just keep password somewhere and use it when the script needs to be updated.

Once you have that ready I can move the script to that email address or we can have a quick call so that I can show you how and do it together.

**Comment by ManiAkasapu** [comment]
Some more info:

Google App script is meant to interact with the Google apps for example, the form Submitted can be stored as a ROW in Google sheet or Send an email or Create a word document from the content submitted. Many possibilities..

**Comment by ManiAkasapu** [comment]
For now,

Please update the file `/[docs](https://github.com/DCC-EX/dcc-ex.github.io/tree/sphinx/docs)/[support](https://github.com/DCC-EX/dcc-ex.github.io/tree/sphinx/docs/support)/create-ticket.rst`

with the new URL which adds **4.0.x** item to the pick-list.

**Comment by FrightRisk** [comment]
It is all working. The script lives on the dccextended gmail account so it can send mail to support@dcc-ex.com, which forwards to whatever account we want to reply from. right now that is another gmail account
