### ISSUE TITLE
Contributor info - level of C++ understanding required

### ISSUE THREAD

**Issue by peteGSX** [DCC-EX/dcc-ex.github.io#240]
Some helpful info from Chris that probably belongs with our contributing info:

Reading any code in any language is always going to require a basic understanding of the language and features, then an understanding of the environment (Arduino in this case, and various CPU versions) plus an understanding of the program features the author is trying to implement (Command parsing and DCC in our case). 

The level of C++  that we use is a relatively small subset of the language as we don't need or use many of the more complex C++ features such as stdio, templates, lambdas, operator overloading, multiple inheritance etc.   but we DO make significant use of the C++ compilers  pre-processor features to automatically customise the code to various CPU or user feature requirements (Wifi, Ethernet etc).
Exrail in particular pulls some  very cunning, but legitimate, stunts with the pre-processor to weave your automations into the code as it's compiled.

The Arduino environment is fundamentally very simple for most programming tasks as there is no massive operating system, GUI or file system to learn. For a very small subset of our code we do need to understand CPU specific interrupts, registers and timers which are almost never encountered by programmers who are not working in embedded systems or device drivers.  In addition, its necessary to learn about the various hardware devices that may be attached although we have tried to reduce the difficulty for the user by adding code that is not necessarily easy to read for the programmer. (Its a trade-off, the complexity has to go somewhere and we don't want the average user to suffer just to make it easy for a handful of programmers.)

Comments in our code could be better but excessive commenting often leads to confusion as things change and in most cases the use of meaningful function and variable names conveys all the information a comment could.
So... anyone wishing to read our code is welcome, and we will do our best to explain anything that's not obvious, but we will expect "basic" c++ skills and a general understanding of Arduinos and DCC which are extensively documented on the web, otherwise you are unlikely to understand our answers.

**Comment by habazut** [comment]
The following subsets of C++ are good to understand:

* pointers instead of the String class. For speed and resource usage the String class is frowned upon and all "strings" are classical null terminated C strings. So it is recommended to read up on how those work.

* static class members. The observant reader finds that there are static and "normal" class members in many classes throughout the code and it is important to keep track of which members exist per object and which only exist once.

* sized types. To save space data types need to be as small as possible and have a predicable size. Even when changing the CPU architecture. So sized types like uint8_t, uint16_t are used where possible.

* eliminate float. As float calculations are CPU intensive and need a lot of program memory on a small AVR CPU these kind of calculations have been eliminated. So we use for example values like 2500mA instead of 2.5A.

**Comment by Asbelos** [comment]
We rely on the ability of the compiler/linker to remove functions that are never called so the resulting binary image is as small as possible. This avoids having to manage separate code for large and small cpus.   

We also rely on the compiler to propagate constants. This, for example, allows us to use a floating point value for motor shield definition but have the float to integer calculation performed by the compiler so the large floating point library is not needed at run time.

**Comment by Asbelos** [comment]
We avoid third party libraries where possible  because they involve additional installation steps, version issues and support problems outside our control.

**Comment by Asbelos** [comment]
Use of bit manipulation operators to pack multiple flags into a byte.

Exrail and the Dcc  Ack manager use "virtual machine" techniques to implement multitasking.

**Comment by peteGSX** [comment]
Will also be updating contribution info for installation of Git, Arduino IDE, and VSCode with PlatformIO as part of this, both for development and documentation needs.
