### ISSUE TITLE
[Documentation Update]: Create DC district page

### ISSUE THREAD

**Issue by peteGSX** [DCC-EX/dcc-ex.github.io#487]
### Documentation details

Need to create the DC district page with lots of caveats around development, changes without notice, how to access the right version for it to work, commands, and motor shield requirements etc.

Must highlight to use a DC loco/cab ID that is *not* one of your DCC loco addresses unless you want dual running of course. 

The command is:
```
<= TRACKLETTER MODE [ID]> : set track output mode

TRACK: A, B, ... H (you can define up to 8 districts, normally you have A and B)

MODE: MAIN PROG DC DCX OFF (explain themselves DCX is like DC but polarity reversed)

ID: DC and DCX need a loco/cab number

<=> : show current status
```

For DC to work your motorshield needs to have Brake and brake must be defined as well (if you have a custom motor shield definition in `config.h` you need to care, otherwise not)

**Comment by habazut** [comment]
There is one more mode which is EXT but I wonder if we should leave that undocumented until we do the "intelligent booster" advertising.  The PWM frequency is 122.55Hz on MEGA and **variable** on ESP32 (just for fun). On other CPUs it's the default PWM frequency (just because noone has changed it yet) which often is around 1000Hz.

Then on another page we need to write how to compose motor driver specifications. But not on this one.
