### ISSUE TITLE
[Documentation Update]: Should the EX-Motorshield 8874 be considered the recommended purchasing part for the motor driver? 

### ISSUE THREAD

**Issue by felicevittoria** [DCC-EX/dcc-ex.github.io#649]
### Documentation details

The purchasing parts page currently shows the following:

a supported Motor Driver
We recommend the [Arduino Motor Shield Rev3](https://store.arduino.cc/collections/shields/products/arduino-motor-shield-rev3)

Should the EX-Motorshield 8874 be considered the recommended purchasing part for the motor driver? 

### Page with issues

https://dcc-ex.com/ex-commandstation/get-started/purchasing.html

**Comment by FrightRisk** [comment]
Yes Felice, absolutely! Thank you for catching this.

**Comment by pmantoine** [comment]
@FrightRisk in the <ahem> rush to get doco done for the EX8874 launch, I looked at doing this aspect of doco change... but the standard motor shield is woven into more than just this page.

Because when you click "Next page" on the purchasing page... all it shows you is initial assembly with the Arduino motor driver. And clearly that needs a **lot** of work to switch... as it's littered with photos, a lot of text assumes issues with the Arduino motor driver that don't exist with the EX8874... etc. etc. etc.

So I left it well alone in that moment... knowing I would regret doing so.

**Comment by peteGSX** [comment]
Looks like it's already covered as one of the recommended options.
