### ISSUE TITLE
Website docs todo

### ISSUE THREAD

**Issue by Condo-Colin** [DCC-EX/dcc-ex.github.io#74]
This is a compilation of Discord conversations about updates to the online docs.
Hopefully it is easy to scroll thru and find things to work on!

Maybe we need to separate these out into individual Issues?

[EX-RAIL docs updates.txt](https://github.com/DCC-EX/dcc-ex.github.io/files/7482469/EX-RAIL.docs.updates.txt)

**Comment by Kcsmith0708** [comment]
Colin,

The two "Request Loco ID’  &  “Drive Away" and the "EXRAIL vs JMRI Controllers"  documents labeled Placeholder I DM you, both were updated a number of times since you originally copied the first txt from the conversation in August.

If you look back in our DM thread you'll see the August dates and draft# are stricken out and replace with new Draft# on 'Drive Away Sept 14 ' and also 'EXRAIL vs JMRI on Sept 28'.

So you could either just copy and replace the text from our DM into this EX-RAIL doc updates,txt,  
Or I can copy the two from DM and give it to you in any format, let me know what you would like it to do.

Also in your compilation .txt document **Ignore** any reference to Throw & Close = 1 & 0 or vise versa.  This has already been decided on and done in the website docs.

Thx
KCS

**Comment by Kcsmith0708** [comment]
Also, When you copy the threads to .txt format it remove all the highlights and spaces and makes it harder to read and comprehend.   Maybe a .rtf or a word doc or google doc would be better.

**Comment by peteGSX** [comment]
Pretty sure this info is now sufficiently covered.
