### ISSUE TITLE
[Documentation Update]: Some corrections to EXRAIL documentation

### ISSUE THREAD

**Issue by FrightRisk** [DCC-EX/dcc-ex.github.io#772]
### Documentation details

EX-RAIL (Automation/Animation)-> Example Objects and Sequences not updated for 5.0 Yet. First sentence has "sequences that you can lean from." Should be "learn".
Next paragraph "Turn Track Power On at Startup" is no longer valid for v5.0, you have to explicitly turn power on with exrail cmd POWERON or cmdline <1>.
And the comment "// if this is at the start of myAutomation.h  This will act like an AUTOSTART sequence" is no longer valid for V5.0

### Page with issues

https://dcc-ex.com/ex-rail/examples.html#example-objects-and-sequences

**Comment by Kcsmith0708** [comment]
I belive the corrections have already been made to this page I could find the open issues. 

I created a PR#890 to add a Version 5 Sample Roster entry for Analog DC engines

**Comment by markr07** [comment]
I updated that section excluding the roster.  PeteGSX reviewed and pushed it to the site.  However, the tabular formatting of the section below was somehow lost.   Most likely due to an oversight on my part.  

Objects : - A three aspect signal connected to Mega2560 I/O pins 22 (red), 23 (amber), and 24 (green) - A two aspect signal connected to Mega2560 I/O pins 25 (red) and 26 (green) - LEDs connected to pins vpins 164 and 165 of an MCP23017 I/O extender - Active low IR sensors connected to Mega2560 I/O pins 40 through 46 - An active low push button on Mega2560 I/O pin 30 

It should look more like...

Objects : 
- A three aspect signal connected to Mega2560 I/O pins 22 (red), 23 (amber), and 24 (green) 
- A two aspect signal connected to Mega2560 I/O pins 25 (red) and 26 (green) 
- LEDs connected to pins vpins 164 and 165 of an MCP23017 I/O extender 
- Active low IR sensors connected to Mega2560 I/O pins 40 through 46 
- An active low push button on Mega2560 I/O pin 30

Unfortunately, don't have sufficient background on how to fix.  Please contact if I can be of further assistance.

Mark

**Comment by peteGSX** [comment]
Easy fix, missing a carriage return/line feed.
