### ISSUE TITLE
Change EX-RAIL command ref tables to HTML.

### ISSUE THREAD

**Issue by Condo-Colin** [DCC-EX/dcc-ex.github.io#79]
This will allow text wrapping in browsers, to show all/extra detail for each command.
Another column may need to be added for expected inputs/outputs?

**Comment by ghost** [comment]
Tables can be more readable with some small alterations in dccex_theme.css

Added it as  [dccex_theme.css.txt]

(https://github.com/DCC-EX/dcc-ex.github.io/files/7565901/dccex_theme.css.txt)

(delete .txt extention to test or upload as new file)

addition 1:  makes the text wrap normal in the table cells


div.wy-table-responsive table td, div.wy-table-responsive table th {
    white-space: normal!important;
}

Alteration 2: aligns tables to left and width is depending on content of the table
(might alter the start page, because of the fact that the images are within a table)


.rst-content table.docutils{
    width: auto;
    margin: 0;
}

One can test this without uploading within Chrome or Firefox 
- Open website page to look at
- F12 utils (CSS section) and load the css from disk to see the differences

**Comment by Condo-Colin** [comment]
Fred converted new list to HTML.
